### ISSUE TITLE
Doesn't load on KDE 5.8.7 LTS

### ISSUE THREAD

**Issue by technic** [ajoshpratt/kwinOverview#10]
Hi,
I am on KDE 5.8.7 LTS, I have installed extension according to instructions. It shows up in the KWin scripts list, but pressing shortcut does nothing, and there is no overview shortcut in my KDE settings. I think this extension failed to load due to some dependency errors.
How to get the load error trace?
Starting `kwin_x11 --replace` doen't show more output.

**Comment by astatide** [comment]
Hi @technic,

The script tends to fail silently if something goes wrong.  In this case, it’s likely because it’s not written against that version of KDE/KWin, so the import statements are almost certainly failing.

Can you give me a little more information?  What distro/version are you using?  It’s unlikely I can provide any immediate answer beyond “update to a more recent version of KDE”, but.

**Comment by technic** [comment]
I have opensuse 42.3.
I wanted to dig myself for the dependencies. But I don't know where to start. Where is that file with something like "can't import foo from baz at line 123" which can help to make it work?

**Comment by technic** [comment]
Ok, I know now how to see qml errors. One needs to set the following environment variable
`QT_LOGGING_RULES="kwin_scripting.debug=true"`

**Comment by technic** [comment]
> Can you give me a little more information? What distro/version are you using?

The answer is simple. I have Qt 5.6 but this plugin requires QtQuick 2.7 which means Qt 5.7. You use mapFromGlobal function which is available starting from Qt 5.7. Could you add Requirements section and state there that we need Qt >= 5.7 for this to work?

I have to admit that my system is quite ancient. For the moment current KDE LTS is 5.12 which requires Qt 5.9 + KDE Frameworks 5.42. So I close this.
